### PR TITLE
Reintroduce python3 in the Dockerfile

### PR DESCRIPTION
**Pull request by mvalkon**
This PR reintroduces the changes made in previous PR's for moving the
Dockerfile and other files to python3. The breaking changes that were
discovered also seem to happen with previous images with python2. More
investigation is needed.

There is no backwards compatibility for python versions here, in case
such is needed a more sophisticated solution is needed.

References #80

### CODE REVIEW

**Comment by mvalkon** [comment]
@scherniavsky with these changes I can run my test case which is in python3.

**Comment by scherniavsky** [comment]
:+1:

**Comment by scherniavsky** [comment]
:+1:

**Comment by bmaher** [comment]
👍

**Comment by scherniavsky** [comment]
:+1:

**Comment by bmaher** [comment]
👍

**Comment by scherniavsky** [comment]
:+1:

**Comment by hjacobs** [comment]
:+1:

**Comment by mvalkon** [comment]
thanks @scherniavsky @bmaher @hjacobs 🎉

**Pull request merged**
