### PR TITLE
re-build the image

### PR DESCRIPTION
**Pull request by scherniavsky**

### CODE REVIEW

**Comment by scherniavsky** [comment]
:+1:

**Comment by thilp** [comment]
Why not retrigger the pipeline at https://dev.zalando.net/pipelines/l-26jvuskor7tqp4wmwf7bsqtnnn ? I find pushing empty commits to master usually tends to make the git history harder to read…

**Comment by scherniavsky** [comment]
because it will try to push image with the same name, which fails

**Comment by tortila** [comment]
👍

**Comment by scherniavsky** [comment]
thx!

**Pull request merged**
