### PR TITLE
Use official base image

### PR DESCRIPTION
**Pull request by girishc13**
Use official base image from the library namespace.

### CODE REVIEW

**Comment by girishc13** [comment]
👍

**Comment by scherniavsky** [comment]
:+1:

**Comment by scherniavsky** [comment]
@girishc13 please add your approval

**Comment by girishc13** [comment]
I have already added my approval but it's not recognized.

**Comment by scherniavsky** [comment]
:+1:

**Comment by M4NTR4** [comment]
:+1:

**Pull request merged**
