### PR TITLE
print_help should not called in specific function

### PR DESCRIPTION
**Pull request by butomo1989**

### CODE REVIEW

**Comment by butomo1989** [comment]
👍

**Comment by scherniavsky** [comment]
With this PR the help will be displayed on every run, irrespective of provided arguments. IMO the help  should only be shown in the following cases below, and should not be followed by any other operations:
- the command is empty
- the command is wrong
- the "--help" argument is provided

**Comment by butomo1989** [comment]
👍

**Comment by scherniavsky** [comment]
:+1:

**Pull request merged**
