### PR TITLE
remove myself from MAINTAINERS

### PR DESCRIPTION
**Pull request by hjacobs**
I will just not have time to be a maintainer for this project.

### CODE REVIEW

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
@diemol so apparently Zappr is not configured correctly (you could merge without two "+1")?

**Comment by diemol** [comment]
Good point @hjacobs, seems like one is enough
https://github.com/zalando-incubator/docker-locust/blob/master/.zappr.yaml#L5
I'll change it to enable reviews.

**Comment by diemol** [comment]
Config updated @hjacobs 👍

**Pull request merged**
