### PR TITLE
Run example scenario before pushing docker image to opensource registry

### PR DESCRIPTION
**Pull request by tortila**
In order to reduce risk of pushing broken changes to `opensource` registry, we decided to run a smoke test before that stage. This will happen on every push to master. In case of failure, docker image will not be pushed to registry.

### CODE REVIEW

**Comment by scherniavsky** [comment]
Could you please add a few minor adjustments:
- a check that would ensure that the report files (requests.json, reports.html) are generated in the ./reports folder and have non-zero sizes
- reduce test time to 5 sec

Thanks!

**Comment by tortila** [comment]
👍

**Comment by scherniavsky** [comment]
:+1:

**Comment by bmaher** [comment]
Looks good to me.
I wonder though if we should move the checks/test into their own test script in the future? That would mean you could also run the test locally too.

**Comment by bmaher** [comment]
👍

**Comment by scherniavsky** [comment]
Good point. And I guess it applies to everything that runs in the delivery.yaml ;)

**Pull request merged**
